#!/bin/bash

PYTHON_FOR_BIN=python3

mkdir -p local/release/tmp

# construct source tarball and put it in misc folder
rm -rf ../dist
rm ../MANIFEST.in
(cd .. ; $PYTHON_FOR_BIN -m build)
rm local/release/tmp/*.tar.gz
cp ../dist/*.tar.gz local/release/tmp
rm -rf ../dist

